/*
Problem 002

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

struct FibIter {
  previous: u32,
  current: u32,
}

impl FibIter {
  fn new() -> FibIter {
    FibIter{
      previous: 0,
      current: 1,
    }
  }
}

impl Iterator for FibIter {
  type Item = u32;
  fn next(&mut self) -> Option<u32> {
    let next = self.previous + self.current;
    self.previous = self.current;
    self.current = next;
    Some(next)
  }
}

pub fn problem002() -> u32 {
  let limit = 4_000_000;

  FibIter::new()
    .filter(|n| n % 2 == 0)
    .take_while(|n| *n < limit)
    .fold(0, |s, e| s + e)
}

#[test]
pub fn test_problem002() {
  assert_eq!(problem002(), 4613732);
}
